[package]
name = "sonar"
version = "0.1.0"
authors = ["Franz Heinzmann (Frando) <frando@unbiskant.org>"]
edition = "2018"

[dependencies]
tantivy = "0.9.1"
serde_json = "1.0.39"
serde = { version = "1.0.90", features = ["derive"] }
log = "0.4.6"

[dev-dependencies]
tempdir = "0.3.7"
