[package]
name = "sonar-tantivy"
version = "0.1.1"
authors = ["Franz Heinzmann (Frando) <frando@unbiskant.org>"]
edition = "2018"

[[bin]]
name = "sonar-tantivy"
path = "src-rust/main.rs"

[dependencies]
tantivy = { git = "https://github.com/Frando/tantivy.git", branch = "segment-meta" }
serde_json = { version = "^1.0", features = ["preserve_order"] }
serde = { version = "^1.0", features = ["derive"] }
log = "^0.4"
uuid = "^0.7"
failure = "^0.1"
varinteger = "^1.0"
once_cell = "^0.2"

[dev-dependencies]
tempdir = "^0.3"
