name: Release

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        arch: [x86_64]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            arch: armv7
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            arch: aarch64
          - os: macOS-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Get tag name
        id: vars
        shell: bash
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      #   uses: actions-rs/cargo@v1
      #   with:
      #     use-cross: true
      #     command: test

      - name: Build (Linux)
        uses: actions-rs/cargo@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      
      - name: Build (Windows or macOS)
        uses: actions-rs/cargo@v1
        if: matrix.os != 'ubuntu-latest'
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package (Linux or MacOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
        run: |
          tar -zvcf sonar-tantivy-${{ steps.vars.outputs.tag }}-${{ matrix.target }}.tar.gz README.md LICENSE -C target/release/ sonar_tantivy
          tar -tzvf sonar-tantivy-${{ steps.vars.outputs.tag }}-${{ matrix.target }}.tar.gz

      - name: Package (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          7z a ${sonar-tantivy-${{ steps.vars.outputs.tag }}-${{ matrix.target }}.zip README.md LICENSE .\target\release\sonar_tantivy.exe
          7z l ${sonar-tantivy-${{ steps.vars.outputs.tag }}-${{ matrix.target }}.zip

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            '*.zip'
            '*.tar.gz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
