name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # disabled windows for now. needs to be fixed.
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        # disabled macos for now, macos github actions do not start at the moment..
        # os: [ubuntu-latest, macOS-latest]
        os: [ubuntu-latest]
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
          # DEBUG: "*,-express*,-hypercore-protocol*,-body-parser*,-babel*,-send,-time"
          RUST_LOG: 'debug'
          RUST_BACKTRACE: 1
          CI: true
